// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyayppkpykaccfgtqpxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5YXlwcGtweWthY2NmZ3RxcHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODgwNTksImV4cCI6MjA3MDQ2NDA1OX0.vegvUVUQ9moxmQIXrRxfGo74JUDeJvs327tMgfgrNfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});